# Query
query order($id: ID!) {
    order: Order(where: { id: $id }) {
        ...order
    }
}

query allOrders {
    allOrders {
        ...order
    }
}

# Mutation
mutation checkout($token: String!) {
    checkout(token: $token) {
        id
        charge
        total
        items {
            id
            name
        }
    }
}

# Fragment
fragment order on Order {
    id
    charge
    total
    user {
        id
    }
    items {
        id
        name
        description
        price
        quantity
        photo {
            image {
                publicUrlTransformed
            }
        }
    }
}
