# Query
query ALL_PRODUCTS_QUERY {
    allProducts {
        id
        name
        price
        description
        photo {
            id
            image {
                publicUrlTransformed
            }
        }
    }
}

# Mutation
mutation CREATE_PRODUCT_MUTATION(
    $name: String!
    $description: String!
    $price: Int!
    $image: Upload
) {
    createProduct(
        data: {
            name: $name
            description: $description
            price: $price
            status: "AVAILABLE"
            photo: { create: { image: $image, altText: $name } }
        }
    ) {
        id
        price
        description
    }
}
