# Query
query products {
    allProducts {
        ...product
    }
}

query product($id: ID!) {
    Product(where: { id: $id }) {
        ...product
    }
}

# Mutation
mutation createProduct(
    $name: String!
    $description: String!
    $price: Int!
    $image: Upload
) {
    createProduct(
        data: {
            name: $name
            description: $description
            price: $price
            status: "AVAILABLE"
            photo: { create: { image: $image, altText: $name } }
        }
    ) {
        ...product
    }
}

mutation updateProduct(
    $id: ID!
    $name: String!
    $description: String!
    $price: Int!
) {
    updateProduct(
        id: $id
        data: { name: $name, description: $description, price: $price }
    ) {
        ...product
    }
}

mutation deleteProduct($id: ID!) {
    deleteProduct(id: $id) {
        ...product
    }
}

# Fragment
fragment product on Product {
    id
    name
    price
    description
    status
    photo {
        id
        altText
        image {
            publicUrlTransformed
        }
    }
}
