# Query
query user {
    authenticatedItem {
        ... on User {
            id
            name
            email

            # TODO: query the cart once we have it
        }
    }
}

# Mutation
mutation login($email: String!, $password: String!) {
    authenticateUserWithPassword(email: $email, password: $password) {
        ... on UserAuthenticationWithPasswordSuccess {
            item {
                id
                name
                email
            }
            sessionToken
        }

        ... on UserAuthenticationWithPasswordFailure {
            code
            message
        }
    }
}

mutation logout {
    endSession
}

mutation register($name: String!, $email: String!, $password: String!) {
    createUser(data: { name: $name, email: $email, password: $password }) {
        id
        name
        email
    }
}

mutation requestPasswordReset($email: String!) {
    sendUserPasswordResetLink(email: $email) {
        code
        message
    }
}

mutation resetPassword($email: String!, $password: String!, $token: String!) {
    redeemUserPasswordResetToken(
        email: $email
        password: $password
        token: $token
    ) {
        code
        message
    }
}
